name: Deploy Django App

on:
  push:
    branches:
      - main
      - develop

jobs:

  deploy-dev:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to DEV EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEV_EC2_IP }}
          username: ubuntu
          key: ${{ secrets.DEV_EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/youtubeclone
            git checkout develop
            git pull origin develop
            sudo systemctl restart gunicorn

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to PROD EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_EC2_IP }}
          username: ubuntu
          key: ${{ secrets.PROD_EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/youtubeclone
            git checkout main
            git pull origin main
            sudo systemctl restart gunicorn